### ISSUE TITLE
Standardize roles

### ISSUE THREAD

**Issue by peterdesmet** [inbo/agouti-export#7]
Roles of contributors [SHOULD](https://specs.frictionlessdata.io/data-package/#contributors) be one of:

- author
- publisher
- maintainer
- wrangler
- contributor (default)

This is how I have currently mapped the Agouti roles:

- [x] ADMIN → maintainer
- [x] PRINCIPAL_INVESTIGATOR → author
- [x] PROJECT_COORDINATOR → ~author~ contributor
- [x] AWAITING_ACCESS → ~contributor~ exclude
- [x] DUMMY → contributor (or exclude?)
- [x] PHOTO_PROCESSOR → contributor
- [x] TAXONOMIC_EXPERT → contributor
- [x] VOLUNTEER → contributor

**Comment by yliefting** [comment]
I would map the roles like this:

ADMIN → maintainer or publisher (admins are only in charge of maintaining Agouti and ensuring data is available, but do not typically lead the project or have data ownership, that falls to the PI)
PRINCIPAL_INVESTIGATOR → author
PROJECT_COORDINATOR → contributor
AWAITING_ACCESS → exclude -> this user does not yet have access to the project
DUMMY → contributor -> this is a person without an account, typically field staff that do not do any processing in Agouti
PHOTO_PROCESSOR → contributor
TAXONOMIC_EXPERT → contributor
VOLUNTEER → contributor
